### ISSUE TITLE
Mosquito short read alignment pipeline - dockerfiles

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/pipelines#11]
Add dockerfiles for all the tools needed by the [vector short read alignment pipeline version 1.1.1](https://github.com/malariagen/pipelines/blob/c7210d93628aaa31f26baa88a92e10322368b78e/docs/specs/short-read-alignment-vector.md).

Part of #2, breaking out as separate issue for convenience.

**Comment by alimanfoo** [comment]
Hi folks, given that dockerfiles might be reused across multiple pipelines, shall we put these in a root level `/dockerfiles` directory in this repo?

**Comment by tnguyensanger** [comment]
Sure.  We have a whole bunch of dockerfiles used in PF7 and for general cromwell/sanger access testing under:  https://gitlab.com/malariagen/gsp/executor/-/tree/master/Docker.

We can move them over.

I'm sure the NIHR amplicon sequencing folks have their own set of docker files.

**Comment by JonKeatley112** [comment]
The Dockerfiles i moved to executor are the ones from amplicon

**Comment by alimanfoo** [comment]
Cool, thanks @tnguyensanger, @JonKeatley112. The specific versions of the tools we need are [in the spec](https://github.com/malariagen/pipelines/blob/c7210d93628aaa31f26baa88a92e10322368b78e/docs/specs/short-read-alignment-vector.md#software).
