### ISSUE TITLE
Provide example crams released by Core Sequencing

### ISSUE THREAD

**Issue by tnguyensanger** [malariagen/pipelines#26]
Share example mosquito crams released from Core Sequencing with @gbggrant  and @kbergin.  

If possible, kill birds with one stone and try to find the smallest valid crams possible to solve #25 .  Querying and sorting IRODS by file size may be a bit fiddly.  Instead, let's choose crams with the fewest reads according to sample metadata from past releases.

**Comment by kbergin** [comment]
Thanks Thuy - I'd be curious how quickly the smallest available cram would run through the pipeline. We may still want to downsample to get the runtime down to 30-60 minutes for quicker development iteration.

**Comment by tnguyensanger** [comment]
@kbergin I've tried to combine #25 and #26 with the same pull request:  https://github.com/malariagen/pipelines/pull/28.  We've provided the smallest example lanelet crams from an actual vector data release (AG1K Phase3).  I'm a bit worried that they don't actually represent a typical vector sample since they are 3 orders of magnitude smaller.  However, we can use them as examples of what a header and format of a Core Sequencing cram will look like.

I'll need to consult with @alimanfoo  and @hardingnj on which samples with lanelet crams would provide a better representation of the typical vector sample so that we can compare pipeline test outputs with confidence.

**Comment by tnguyensanger** [comment]
From slack conversation with @kbergin Jun 3, 2020:
> 
> So we usually look for:
> Plumbing tests, automated on small data that runs quickly but still works thorugh the whole pipeline
> Scientific tests - these would be on a more normal size sample, maybe a few, that can take longer to run but ideally a day or less and could be automated on PRs to master before release, or could be manually kicked off when needed
> We can also do an even larger set of data to fully validate the pipeline for this first pass, but this could be the same as the scientific test data depending on your preference.
> For testing upgrades to infrastructure we usually run much larger scale tests on many samples but that can be a later thing.
