### ISSUE TITLE
Add script to test whether people have access to Sanger Farm5

### ISSUE THREAD

**Issue by tnguyensanger** [malariagen/pipelines#3]
Suggestions from @jon.keatley.aspis on slack Mar 26

> Jon Keatley  16:17
> ssh farm5-login
> ls /lustre
> check for .irods in ~/
> busers & bugroup

Any new user should have access to:
- farm5 head nodes
- lustre disk
- nfs disk
- IRODS
- LSF scheduler

**Comment by alimanfoo** [comment]
Hi @tnguyensanger, I think we should try to keep this repo as a place for non-sanger-specific code, i.e., the core WDL and docker files.

**Comment by alimanfoo** [comment]
Closing as out of scope for this repo.
