### ISSUE TITLE
Add platform argument to build_pipeline_release script

### ISSUE THREAD

**Issue by gbggrant** [malariagen/pipelines#38]
Currently the pipeline wdl files for gcp and farm5 are extremely similar.  It would be great to make these one file and pass an argument to the build_pipeline_release script which would specify the platform to generate the wdl for.

A concern about this is that in making the pipeline wdl platform non-specific (for instance by adding a placeholder field for the platform-to-be-specified) this might make the wdl non-valid for our wdl checking tool (miniwdl).

**Comment by alimanfoo** [comment]
Hi @gbggrant, is this still relevant or could we close?

**Comment by gbggrant** [comment]
This can be closed.
