### ISSUE TITLE
Determine final lanelet manifest fields required for vector alignment and genotyping 

### ISSUE THREAD

**Issue by tnguyensanger** [malariagen/pipelines#54]
We need to solidify the final manifest fields required for vector alignment and genotyping.  Right now, we are using fields found in https://github.com/malariagen/pipelines/blob/master/pipelines/short-read-alignment-and-genotyping-vector/farm5/input_files/validation/validation_lanelets_farm5_local.tsv

- sample_id	
- run_ena	
- irods_path	
- bam_path	
- cram_path	
- read1_path	
- read2_path

We don't need all these fields for the production manifest passed in to the batch-irods import-alignment-genotyping vector pipelines.  At the moment, we probably only need:

- sample_id
- irods_path

However, run_ena is used as an input in the per-lanelet-alignment vector pipelines.  

We will need to solidify the final inputs in the manifest that we need to keep track of samples and their progress in the production system.  For example, we don't need the study in the input manifest to run the pipelines.  But will we need the study stored as a workflow label/metadata so that we can query for it later in the future?

**Comment by alimanfoo** [comment]
Hi @tnguyensanger, 

I'm happy to provide just `sample_id` and `irods_path` if that's all that is really needed.

I will be asking for pipeline runs to be scheduled and tracked by sample set, and I will provide one lanelet manifest for each sample set. The only question I'll be asking is, have all the samples in a given manifest finished alignment and genotyping yet? So when you're running this pipeline, you'll need to be able to figure that out somehow. But I don't think that requires any extra metadata fields within the manifest. 

No other queries are needed.
